USE WAREHOUSE COMPUTE_WH;
USE SCHEMA ECOM_DB.ECOM_DW;

-- Produce cumulative revenue over time to understand long-term growth behavior.
SELECT DISTINCT(DIM_DATE.YEAR) AS Year, SUM(NET_AMOUNT) OVER (PARTITION BY DIM_DATE.YEAR ORDER BY DIM_DATE.YEAR) AS Revenue FROM FACT_ORDER_LINE
INNER JOIN DIM_DATE ON FACT_ORDER_LINE.DATE_KEY = DIM_DATE.DATE_KEY
ORDER BY Year;