-- Compare current month performance with previous month to detect growth or decline.
WITH MONTHLY_TOTALS AS (
    SELECT
        DIM_DATE.YEAR,
        DIM_DATE.MONTH,
        SUM(FACT_ORDER_LINE.NET_AMOUNT) AS CURRENT_MONTH_TOTAL,
        LAG(SUM(FACT_ORDER_LINE.NET_AMOUNT), 1) OVER (ORDER BY DIM_DATE.YEAR, DIM_DATE.MONTH) AS PREVIOUS_MONTH_TOTAL
    FROM FACT_ORDER_LINE
    INNER JOIN DIM_DATE ON FACT_ORDER_LINE.DATE_KEY = DIM_DATE.DATE_KEY
    GROUP BY DIM_DATE.YEAR, DIM_DATE.MONTH
)
SELECT *,
CASE WHEN CURRENT_MONTH_TOTAL > PREVIOUS_MONTH_TOTAL THEN 'GROWTH' ELSE 'DECLINE' END AS PERFORMANCE_INDICATOR
FROM MONTHLY_TOTALS
WHERE MONTH = MONTH(CURRENT_DATE());
