-- Rank brands inside each category based on total profit generation.
WITH BRAND_RANKS AS(
    SELECT DIM_CATEGORY.CATEGORY_KEY, DIM_CATEGORY.CATEGORY_NAME, DIM_PRODUCT.BRAND, SUM(PROFIT_AMOUNT) AS ProfitAmount       FROM FACT_ORDER_LINE
    INNER JOIN DIM_CATEGORY
    ON FACT_ORDER_LINE.CATEGORY_KEY = DIM_CATEGORY.CATEGORY_KEY
    INNER JOIN DIM_PRODUCT
    ON FACT_ORDER_LINE.PRODUCT_KEY = DIM_PRODUCT.PRODUCT_KEY
    GROUP BY DIM_CATEGORY.CATEGORY_KEY, DIM_CATEGORY.CATEGORY_NAME, DIM_PRODUCT.BRAND
) 

SELECT CATEGORY_NAME, RANK() OVER(PARTITION BY CATEGORY_KEY ORDER BY ProfitAmount DESC) AS BRAND_RANK, BRAND, ProfitAmount FROM BRAND_RANKS;