USE WAREHOUSE COMPUTE_WH;
USE SCHEMA ECOM_DB.ECOM_DW;

-- Rank customers based on recency of activity.
WITH CUSTOMER_ACTIVITY AS (
    SELECT CUSTOMER_KEY, MAX(FACT_ORDER_LINE.DATE_KEY), CURRENT_DATE() - MAX(DIM_DATE.FULL_DATE) AS LAST_ACTIVITY FROM FACT_ORDER_LINE
    INNER JOIN DIM_DATE
    ON FACT_ORDER_LINE.DATE_KEY = DIM_DATE.DATE_KEY
    GROUP BY CUSTOMER_KEY
) 
SELECT CUSTOMER_KEY, DENSE_RANK() OVER (ORDER BY LAST_ACTIVITY) AS ACTIVITY_RANK, LAST_ACTIVITY 
FROM CUSTOMER_ACTIVITY
ORDER BY LAST_ACTIVITY,CUSTOMER_KEY ASC;