USE WAREHOUSE COMPUTE_WH;
USE SCHEMA ECOM_DB.ECOM_DW;

-- Assess revenue volatility for each product.
WITH PRODUCT_REVENUE AS (
    SELECT FACT_ORDER_LINE.PRODUCT_KEY, DIM_PRODUCT.PRODUCT_NAME, DIM_DATE.YEAR, DIM_DATE.MONTH, SUM(FACT_ORDER_LINE.NET_AMOUNT) AS REVENUE
    FROM FACT_ORDER_LINE
    INNER JOIN DIM_DATE
    ON FACT_ORDER_LINE.DATE_KEY = DIM_DATE.DATE_KEY
    INNER JOIN DIM_PRODUCT
    ON FACT_ORDER_LINE.PRODUCT_KEY = DIM_PRODUCT.PRODUCT_KEY
    GROUP BY FACT_ORDER_LINE.PRODUCT_KEY, DIM_PRODUCT.PRODUCT_NAME, DIM_DATE.YEAR, DIM_DATE.MONTH
)

SELECT PRODUCT_KEY, PRODUCT_NAME, YEAR, MONTH, REVENUE, STDDEV(REVENUE) OVER (PARTITION BY PRODUCT_KEY) AS REVENUE_VOLATILITY
FROM PRODUCT_REVENUE
ORDER BY PRODUCT_KEY, YEAR, MONTH;